INSERT INTO product VALUES(1, 'Ordinateur portable', 350);
INSERT INTO product VALUES(2, 'Aspirateur Robot', 500);
INSERT INTO product VALUES(3, 'Table de Ping Pong', 750);
INSERT INTO category VALUES(1, 'Homme');
INSERT INTO category VALUES(2, 'Femme');
INSERT INTO category VALUES(3, 'Enfant');
INSERT INTO category_products_id VALUES(1, 2);
INSERT INTO category_products_id VALUES(1, 3);
INSERT INTO category_products_id VALUES(2, 1);
INSERT INTO category_products_id VALUES(3, 3);
INSERT INTO product_categories_id VALUES(1, 2);
INSERT INTO product_categories_id VALUES(2, 1);
INSERT INTO product_categories_id VALUES(3, 1);
INSERT INTO product_categories_id VALUES(3, 3);